# Generated by Django 4.0.4 on 2022-07-26 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branchers', '0001_initial'),
        ('vendors', '0001_initial'),
        ('Edition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ro_date', models.DateField()),
                ('Add_type', models.CharField(max_length=255)),
                ('Size', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst', models.IntegerField(default=1)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_amunt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branchers.branches')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_order', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_release_order', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='R_edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edition_name', to='Edition.edition')),
                ('ro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edition', to='releaseorder.release_order')),
            ],
        ),
        migrations.CreateModel(
            name='Pub_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('ro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pub_date', to='releaseorder.release_order')),
            ],
        ),
    ]
