# Generated by Django 4.0.4 on 2022-07-28 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releaseorder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release_order',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='release_order',
            name='modified_by',
        ),
    ]
