# Generated by Django 4.0.4 on 2022-06-29 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EditionSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EditionDate', models.DateField(auto_now_add=True)),
                ('EditionName', models.CharField(blank=True, default=True, max_length=255)),
                ('EditionShowRoom', models.CharField(blank=True, default=True, max_length=255)),
                ('EditionLocation', models.CharField(blank=True, default=True, max_length=255)),
                ('EditionValue', models.CharField(blank=True, default=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShowRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_CODE', models.CharField(max_length=5, null=True)),
                ('SHORT_CODE', models.CharField(max_length=10, null=True)),
                ('TYPE', models.CharField(blank=True, max_length=10, null=True)),
                ('FLATE_HOUSE_NO', models.CharField(max_length=1000, null=True)),
                ('STREET_BUILDING_NAME', models.CharField(max_length=500, null=True)),
                ('LANDMARK', models.CharField(max_length=255, null=True)),
                ('PINCODE', models.CharField(max_length=6, null=True)),
                ('AREA', models.CharField(max_length=255, null=True)),
                ('TALUK', models.CharField(max_length=255, null=True)),
                ('DISTRICT', models.CharField(max_length=255, null=True)),
                ('STATE', models.CharField(max_length=255, null=True)),
                ('STATUS', models.CharField(max_length=255, null=True)),
                ('DOB', models.DateField()),
                ('CLOSED', models.DateField(blank=True, null=True)),
                ('SHOWROOM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_detials.showroom')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_ID', models.CharField(max_length=10, null=True)),
                ('Full_Name', models.CharField(max_length=255, null=True)),
                ('Designation', models.CharField(max_length=560, null=True)),
                ('Sub_Regions', models.CharField(max_length=100, null=True)),
                ('Location_Type', models.CharField(max_length=255, null=True)),
                ('Work_Area_Code', models.CharField(max_length=255, null=True)),
                ('Office_City', models.CharField(max_length=255, null=True)),
                ('Office_State', models.CharField(max_length=255, null=True)),
                ('Region', models.CharField(max_length=225, null=True)),
                ('Department_Code', models.CharField(max_length=255, null=True)),
                ('Department', models.CharField(max_length=255, null=True)),
                ('Gender', models.CharField(max_length=255, null=True)),
                ('Date_of_Birth', models.DateField(null=True)),
                ('Employee_Type', models.CharField(max_length=255)),
                ('Work_Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_detials.showroom')),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District', models.CharField(max_length=255)),
                ('State', models.CharField(blank=True, max_length=255, null=True)),
                ('Edition', models.CharField(blank=True, max_length=255, null=True)),
                ('Pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_detials.publication')),
            ],
        ),
    ]
