# Generated by Django 4.0.4 on 2022-07-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_remove_purchase_order_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
