# Generated by Django 4.0.1 on 2022-08-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_alter_item_net_amount_alter_item_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
