# Generated by Django 4.0.8 on 2022-12-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_of_material',
            name='material_price',
            field=models.IntegerField(),
        ),
    ]
