# Generated by Django 4.0.8 on 2022-12-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0002_alter_bill_of_material_material_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_of_material',
            name='material',
            field=models.TextField(max_length=255),
        ),
    ]
